### ISSUE TITLE
Change PermissionTemplate workflow_name column to workflow_id

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra-labs/hyrax#191]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jcoyne](https://github.com/jcoyne)**
_Thursday Dec 01, 2016 at 17:19 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2954_

----

Becuase the workflows are also in the database. https://github.com/projecthydra/sufia/blob/master/db/migrate/20161021175854_create_permission_template.rb#L6

**Comment by scholarworks** [comment]
Going through the code on this one, I think it may be premature to make these changes, if we decide to at all. It seems to affect the generation of the default admin_set and default permission template and seems odd to specific a specific number (1) instead of the name 'default'.

I'm thinking we should backlog this until a time where we may have a UI that can be used to specify the default admin_set, workflow, etc. Until then, the name is probably the best strategy.

I'd be happy to hear the feedback from @jcoyne, @mjgiarlo and @jeremyf on this however.

**Comment by mjgiarlo** [comment]
@jcoyne ticketed this, so I defer to him as to how necessary this work is.

**Comment by jcoyne** [comment]
This is quite necessary unless we can guarantee that `Sipity::Workflow#name` is an immutable value. Otherwise we risk loosing referential integrity.

**Comment by scholarworks** [comment]
@jcoyne thanks. That was my original intent before the break, but then seeing the default related work made me question it. In this case I will continue to work through the process. Should have a PR today or so.

**Comment by jeremyf** [comment]
Given that PermissionTemplate is an ActiveRecord object (as is Sipity::Workflow), I agree that it should be `workflow_id` and have it be a `belongs_to` relationship.

The other thing to then consider is what is the dependent relationship between Sipity::Workflow and PermissionTemplate? I advocate for `has_many :permission_templates, dependent: : restrict_with_exception` (e.g. don't allow a workflow to be deleted if it is assigned to one or more permission templates)

http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_many

**Comment by scholarworks** [comment]
@jeremyf that makes sense to me. I started to go down the relationship path when I realized that's what _id would be doing anyway. I'll continue that unless there are any objections.

**Comment by jeremyf** [comment]
@jcoyne Should we add an issue along the lines of "Ensure that the Sipity::Workflow name is immutable"
