### ISSUE TITLE
Need to be able to set the default workflow

### ISSUE THREAD

**Issue by vantuyls** [projecthydra-labs/hyrax#220]
Hyrax comes off the shelf with a zero-step workflow as the default. Some users may want to have the default workflow behave otherwise (e.g. a 2 step mediation workflow), so we need the ability to define a workflow as the default workflow.

**Comment by mjgiarlo** [comment]
@vantuyls @projecthydra-labs/hyrax-ui-ux-advisors Anyone inclined to offer mock-ups for this, or ideas on where we should place this feature in the UI? 

(Cc: @ggeisler)

**Comment by ggeisler** [comment]
It looks like there is already a Workflows section under Configuration (in Hyku, at least, but not designed by me) so that seems like a logical place for it to me. 

(Although I would design what is currently under Workflows differently, since the Review page is not what I'd consider "configuration." I think one-time or occasional configuration tasks should be clearly separated from more regular, day-to-day actions, which is what the Review page appears to be intended for).

**Comment by jcoyne** [comment]
I think this is already possible. Edit the admin set and set the workflow you want

**Comment by vantuyls** [comment]
@jcoyne it is possible to use the admin set interface for an admin set, but this issue is to set the default workflow to something other than the zero-step workflow. Maybe that wasn't clear in the original issue?

**Comment by jcoyne** [comment]
@vantuyls You have an default admin set.  It has a workflow.  It is the default workflow.  So, you should be able to change it.

**Comment by mjgiarlo** [comment]
@jcoyne Maybe I was confused when I created the issue because my tenant in our demo instance doesn't have the default admin set.

**Comment by mjgiarlo** [comment]
@jcoyne @vantuyls Perhaps this ticket should be more like: "Default admin set should be created earlier than when the first work w/o an admin set is submitted." ?

**Comment by jcoyne** [comment]
Yep!

**Comment by mjgiarlo** [comment]
@jcoyne OK, will do.

**Comment by mjgiarlo** [comment]
Closing this ticket in favor of a new one, given the discussion so far. Is that OK, @vantuyls? Re-open if not!
