### ISSUE TITLE
Admin Sets should be closed for deposit by default

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra-labs/hyrax#357]
Admin Sets are currently open by default, despite the fact that we've created a new role for depositing to Admin Sets. Admin Sets should instead be closed by default, with the ability for Admin Set Managers to open them up for deposit by all registered users (via some sort of widget -- design needed here -- in the new/edit forms).

Note: the Default Admin Set should remain OPEN by default, but should be able to be made closed via the above widget.

Cc: @hannahfrost @ggeisler

**Comment by ggeisler** [comment]
@mjgiarlo @hannahfrost Proposed design below. There's a lot of explanation but my recommendation comes down to:

* Add the Registered Users group to the Depositor role for the default admin set only, when the app is first deployed
* Add a button labelled "Allow all registered users to deposit" (`btn-info btn-sm`) just above the current Depositors table whenever that table **does not** include the Registered Users group. Clicking the button adds the Registered Users group to the Depositor role.
* Hide that button whenever the Depositors table **does** include the Registered Users group 

## Details
I'll offer a couple of alternatives for the "widget" that enables the Admin Set Manager to easily open an admin set up for deposit: a button and a checkbox. I recommend the button version, because I unchecking the checkbox duplicates the Remove button functionality that is already there and I think that has the potential for confusion (and hiding a checkbox when it is in one state seems wrong to me).

## Button Version

Two scenarios: the default admin set and non-default admin sets.

### Default Admin Set

There's no need for the widget in this scenario because we'll assign the Registered Users group to the Depositor role by default. The Admin Set Manager can easily revoke that decision by clicking the Remove button.

![button-step2](https://cloud.githubusercontent.com/assets/101482/23043071/55af77b2-f458-11e6-8a00-2e12a0df75e5.png)

If the Admin Set Manager does indeed remove the Registered Users group, the widget should appear as described below.

### Non-Default Admin Sets

The Registered Users group is not added by default but because this could be a common goal for many admin sets, we want to make it easy and clear to the Admin Set Manager who wants to open the admin set up. So when the Registered Users group is not currently assigned to the Depositor role, we show a button:

![button-step1](https://cloud.githubusercontent.com/assets/101482/23043207/d27d76cc-f458-11e6-8f52-96bb168e1921.png)

(Note that this mockup assumes that ticket #429 is completed -- that's where the _No depositors have been added to this administrative set_ line comes from -- but I don't think that ticket is a blocker for this one; they can be done in either order.)

We would show the button in the same way for the default admin set if the Admin Set Manager has removed the Registered Users group.

I think we still want to show the button if other users have been added as Depositors:

![button-step3](https://cloud.githubusercontent.com/assets/101482/23044317/e763aab2-f45c-11e6-9d6a-513e81f524ac.png)


But when the Admin Set Manager clicks this button to add the Registered Users group to the Depositor role, I think we should then hide the button, since it has no purpose in that state. 

![button-step2](https://cloud.githubusercontent.com/assets/101482/23043478/a5b90682-f459-11e6-8644-f2b5e20b1673.png)

## Alternative Widget

If we went with a checkbox instead of a button, and didn't hide it, it would look like this:

![checkbox-step1](https://cloud.githubusercontent.com/assets/101482/23043511/c31c1db8-f459-11e6-93ff-0c8f9dadf4c4.png)

![checkbox-step2](https://cloud.githubusercontent.com/assets/101482/23043525/d2e2c9ea-f459-11e6-9977-a2725efa7a41.png)

![checkbox-step3](https://cloud.githubusercontent.com/assets/101482/23043549/e3fbd9ce-f459-11e6-950d-937d8b23e491.png)

With that approach, the checkbox is acting as a toggle, which seems clear enough. But it also is potentially confusing because unchecking the checkbox does the same thing as the Remove button in the Registered Users row.

**Comment by hannahfrost** [comment]
@ggeisler This makes sense to me. I have a slight preference for the Button version.

**Comment by mjgiarlo** [comment]
@julesies reported this as a bug in Sufia as well: https://github.com/projecthydra/sufia/issues/3108 I have asked how high of a priority this is for her use cases, to get a sense of whether we should do this in Sufia or Hyrax.

**Comment by mjgiarlo** [comment]
We believe Admin Sets are now closed for deposit.

## TODO

- [ ] create a new ticket to implement the "Allow all registered users to deposit" functionality mocked-up above.

**Comment by mjgiarlo** [comment]
Created #994. Closing.
