### ISSUE TITLE
Broken image icon (with "Nope" label) displays after saving a new work

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyrax#392]
Immediately after I save a new work, while my files are being processed in the background, on the work page, just below the work title, a broken image icon and an adjacent label of "Nope" are displayed.

I would expect to see some other visual icon or explanatory text in that space, something that makes clear that the work's files are in process.

**Comment by hannahfrost** [comment]
@mjgiarlo I don't know if this is a bug or if it needs design.

**Comment by mjgiarlo** [comment]
@hannahfrost This looks like very old code that came over from Curate:

https://github.com/projecthydra-labs/hyrax/blob/master/app/views/hyrax/base/_representative_media.html.erb

Perhaps instead of rendering the (unavailable) nope image, we should hook into the default image code here? https://github.com/projecthydra-labs/hyrax/pull/353/commits/c9094e669bf3ede719585959db804985e0571d85

Thoughts, @jcoyne? Feels like a bug to me.
