### ISSUE TITLE
My approved works aren't showing up on My Works page

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyrax#448]
I am a depositor who submitted two works (one generic, one image) to an Admin Set with mediated workflow and who received a notification for each as they were approved, but the works not listed on My Works page. I would expect to see both of them listed there.

A third work that I submitted to the Default Admin Set, which has no mediation steps, is showing on My Works. It is the only work showing on My Works.

**Comment by jcoyne** [comment]
The problem here is that "My works" is filtering works that you are the depositor of *and* have edit access to.  Now that we have workflows, we've taken away the ability of someone to edit a work they have deposited, thus it's not showing on the page.  I think we should change "My works" to show all the works I have deposited, even those we don't have edit access to.
