### ISSUE TITLE
Missing breadcrumbs on Groups pages

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyrax#467]
The two pages under Users and Groups on the admin dashboard -- Manage Users and Manage Groups -- do not show the breadcrumbs. This is not consistent with the other pages on the admin dashboard, and I would expect to find them for a better navigation experience.

**Comment by laritakr** [comment]
I've added it to my new users page that is in the works. From our discussions last week, I am under the assumption that the existing users page is most likely not going to remain, so I would assume it doesn't need to be retrofitted with breadcrumbs. If I'm wrong on this, please let me know.

Manage groups page is in hyku rather than hyrax, so that would be a separate issue from manage users, and would need to be covered by this issue.

**Comment by hannahfrost** [comment]
Thanks, @laritakr. You are correct: no need to add breadcrumbs to the existing page. Let's wait for the page that you are working on in https://github.com/projecthydra-labs/hyrax/issues/247. 

I'm editing the title of this issue so it just concerns the Groups pages.
