### ISSUE TITLE
Footer covers dashboard sidebar

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyrax#628]
To be done post #482

**Comment by jcoyne** [comment]
@ggeisler This is a problem do to adding more items to  the .sidebar, which you gave `position: fixed`

**Comment by ggeisler** [comment]
@jcoyne Yeah, I see what happens when the sidebar is longer. Position:fixed doesn't seem to be a viable solution then. So, yes, feel free to revert the updates in https://github.com/projecthydra-labs/hyrax/pull/582.

At that point I still think it's important we find a solution to making the sidebar more visually clear, or at least not have its background color spill over to the main content area. An easy approach would be to simply change the background color of `#sidebar` to `#f0f0f0`, which would match the background color of the rest of the non-header and footer areas (so the whole content area would have the same background color and there would be no visible dividing line between sidebar and main content area). We'd also have to update the sidebar link colors to work with `#f0f0f0` but that wouldn't be difficult. I could do all of this but not until next week sometime, but anyone else is also welcome to do it.

The drawback of the easy way out above would be for future implementors who wanted to customize the content background colors and use a different color for the sidebar and main content sections. They'd have to figure out a way to solve the problem I was trying to solve with the position: fixed approach.
