### ISSUE TITLE
Submitting workflow action form without picking an action causes an error.

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyrax#671]
It should either do nothing, or not activate the submit button until an action is chosen.

**Comment by jcoyne** [comment]
I think @mjgiarlo fixed this.

**Comment by mjgiarlo** [comment]
Not fixed.

**Comment by darrenleeweber** [comment]
Steps to reproduce bug:
- change the workflow of the default admin set to be one-step mediated deposit.
- then deposit a work (make sure the default admin set is selected in the relationships tab of the 'add new work' view)
- it may be necessary to use two users to reproduce this:
  - set up the admin set with your admin user
  - then deposit a work with another new user
- then your admin user should get a notification that a work is waiting for review
  - click the link in the notification
  - this will take you to the work show view
    - look for the "review and approval" widget at the bottom of the window
    - expand it and click the submit button without selecting a radio button

**Comment by laritakr** [comment]
UI design on this issue is needed:  

The form has several validations:

https://github.com/projecthydra-labs/hyrax/blob/master/app/forms/hyrax/forms/workflow_action_form.rb#L37-L48

The controller routes any inability to update the form to an "unauthorized" page. PR https://github.com/projecthydra-labs/hyrax/issues/1013 now handles the exception error, but the controller routes to this same unauthorized page. 

https://github.com/projecthydra-labs/hyrax/blob/master/app/controllers/hyrax/workflow_actions_controller.rb#L16

![screen shot 2017-05-22 at 3 54 33 pm](https://cloud.githubusercontent.com/assets/17851674/26325935/005be0f8-3f07-11e7-9162-f281fd8c2c2f.png)

The desired behavior in the UI needs to be determined.

**Comment by mjgiarlo** [comment]
@laritakr Should :point_up: be a new issue? If so, do you mind creating it?
